<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="ELDOBLRQAW7024" name="seleniumassignment.iTestListenerRetry_TestCase11_12" tests="5" failures="1" timestamp="08 Jul 2021 14:25:33 GMT" time="7.076" errors="0">
  <testcase name="LogInToApp" time="6.170" classname="seleniumassignment.iTestListenerRetry_TestCase11_12"/>
  <testcase name="method1" time="0.347" classname="seleniumassignment.iTestListenerRetry_TestCase11_12">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.179" classname="seleniumassignment.iTestListenerRetry_TestCase11_12">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at seleniumassignment.iTestListenerRetry_TestCase11_12.method1(iTestListenerRetry_TestCase11_12.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.186" classname="seleniumassignment.iTestListenerRetry_TestCase11_12">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.194" classname="seleniumassignment.iTestListenerRetry_TestCase11_12">
    <skipped/>
  </testcase> <!-- method1 -->
</testsuite> <!-- seleniumassignment.iTestListenerRetry_TestCase11_12 -->
